jwt:
  secret: 'oGUpl6rQ1oe0x4zaZqK9xt6O1FmZEAlR1Rdnep9x1HSJwkUFnlFHRoksGwv8pXN'
  expiration_time: 9620000000
spring:
  datasource:
    url: jdbc:h2:mem:board-db
    username: root
    password: root
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080